# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install dependencies (using --frozen-lockfile for consistency)
RUN pnpm install --frozen-lockfile

# Copy all project files
COPY . .

# Build the project
RUN pnpm run build

# Expose port if needed (optional, not used by MCP)
# EXPOSE 3000

# Start the MCP server
CMD ["node", "./dist/index.js"]
